[colors.bright]
black = "#545875"
blue = "#7AA2F7"
cyan = "#2AC3DE"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#E0AF68"

[colors.normal]
black = "#1A1B26"
blue = "#7AA2F7"
cyan = "#2AC3DE"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#E0AF68"

[colors.primary]
background = "#1A1B26"
foreground = "#A9B1D6"

[font]
size = 16

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
