#!/bin/sh

docker run --rm \
    -v $(pwd):/app \
    -v ${COMPOSER_HOME:-$HOME/.composer}:/tmp \
    -v $SSH_AUTH_SOCK:/ssh-auth.sock \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -u $(id -u):$(id -g) \
    -e SSH_AUTH_SOCK=/ssh-auth.sock \
    php74-composer "$@"
