#!/bin/bash

host_project_root="/home/gustaf/src/sweetspot-api-platform"
docker_args=""

for arg in "$@"; do
  docker_args="$docker_args $arg"
done

output=$(docker run -it -v ${host_project_root}:${host_project_root} -w ${host_project_root} php74-phpstan bash)

echo $output
