#!/bin/bash

host_project_root="/home/gustaf/src/sweetspot-api-platform"
docker_args=""

for arg in "$@"; do
  docker_args="$docker_args $arg"
done

docker run -v ${host_project_root}:${host_project_root} -w / php74-phpmd phpmd ${docker_args}

