#!/bin/bash

host_project_root=$(pwd)

for arg in "$@"; do
  docker_args="$docker_args $arg"
done

docker run -v ${host_project_root}:${host_project_root} -w ${host_project_root} php74-phpstan phpstan --memory-limit=4g $docker_args

