# Personal directories
export DOTFILES="$HOME/sync/sync/src/dotfiles"

export POLYBAR_DIR="$DOTFILES/polybar"
export I3_DIR="$DOTFILES/i3"
export ROFI_DIR="$DOTFILES/rofi"

export NOTES="$HOME/sync/notes"
export SYNC="$HOME/sync/sync"

# XDG Base Directory Specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/share"
export XDG_STATE_HOME="$XDG_CONFIG_HOME/state"

# ZSH configuration
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"

# History configuration
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE 
export KEYTIMEOUT=1

# Editor settings
export EDITOR="nvim"
export VISUAL="$EDITOR" # Reuse the EDITOR value

# Browser setting, with a fallback if Firefox is not installed
if command -v firefox >/dev/null; then
    export BROWSER=$(command -v firefox)
else
    echo "Firefox is not installed. Please set the BROWSER variable manually."
fi

# Path settings
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if [ -d "$XDG_CONFIG_HOME/bin" ]; then
    export PATH="$XDG_CONFIG_HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$DOTFILES/bin/:$PATH"

# fzf configuration
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


export QT_SCALE_FACTOR=2
export GDK_SCALE=2
