#!/bin/bash

host_project_root="/home/gustaf/src/sweetspot-api-platform"

for arg in "$@"; do
  docker_args="$docker_args $arg"
done

docker run -v ${host_project_root}:${host_project_root} -w / php74-phpcs $docker_args

